name: hpc_students
description: "HPC Students là ứng dụng hữu ích dành cho sinh viên trường CĐCNBKHN."

publish_to: none

version: 1.2.1+8

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.9
  flutter_html: 3.0.0-beta.2
  wakelock_plus: ^1.2.2
  provider: ^6.0.0
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.8
  html: ^0.15.0
  xml: ^6.5.0
  flutter_widget_from_html_core: ^0.15.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.0.20
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.3
  audioplayers: ^6.1.0
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.3
  screenshot: ^3.0.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  webview_flutter: ^4.9.0
  flutter_inappwebview: ^6.1.4
  cached_network_image: ^3.4.1
  flutter_localization: ^0.2.2
  curved_labeled_navigation_bar: ^2.0.2
  image_picker: ^1.1.2
  dio: ^5.7.0

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  #flutter_native_splash: ^2.2.16

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/logoSplash.png
    - assets/avatar.png
    - assets/audio/notification.mp3
    - assets/doi-mat-khau.svg
    - assets/AccessControl/Parking.svg
    - assets/AccessControl/Parked.svg
    - assets/AccessControl/ParkingAccessDenied.svg
    - assets/AccessControl/GetCarSuccessfully.svg
    - assets/yeuCau/khong-co-yeu-cau.svg
    - assets/Blog/
